### ISSUE TITLE
Trouble understanding the X_best found: []

### ISSUE THREAD

**Issue by jaronski** [We-R22/pid_tuning#1]
Hello WE-R22,
i would like to try and evaluate the pid_tuning for a robot manipulator arm in gazebo. I have setup everything like in the scara_robot_description example and managed to go thru 263 generations and got the X_best founded written in the best_pid_values_DE.txt file.

What i don't understand is, which value P,I,D corresponds to which controller? i defined A=5 joints and m=15 (5 Joints x 3 values(pid)) so i expected an output of 15 values but in my case i got a total of 17 values written as X_best found. 

For the scara tutorial i get also an output of 11 values and would have expected 9 as for the 3 joints. In the tutorial output i also don't understand how the values correspond to which joint and to which p or i or d.

can you help me with an explanation here?

**Comment by WeR-22** [comment]
Hi jaronski, the last two columns in the txt file correspond to the Sum of Violation Restrictions (SVR) and the evaluation of the objective function for the best solution. So you don't need to consider the last two columns in any case, we decide to save these two columns only for reference. The first three columns correspond to your first controller gains P, I, and D, and so on for each controller.

**Comment by jaronski** [comment]
Thank you for your explanation
